name: breeze_jp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  # 状态管理  
  flutter_riverpod: ^2.5.1
  # SQLite
  sqflite: ^2.3.3
  path: ^1.9.0
  # 路由导航
  go_router: ^15.1.2
  # 音频库
  just_audio: ^0.9.40
  # 文本组件
  ruby_text: ^3.0.3
  # 动画
  flutter_animate: ^4.5.0
  # 手势操作
  gesture_x_detector: ^1.1.1
  # JSON
  json_annotation: ^4.9.0
  # 英文转罗马音
  kana_kit: ^2.1.1
  # 沙盒路径获取
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/database/breeze_jp.sqlite
    - assets/audio/words/
    - assets/audio/examples/
    