name: breeze_jp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # 国际化
  intl: ^0.20.2
  # 状态管理  
  flutter_riverpod: ^3.0.3
  # SQLite
  sqflite: ^2.3.3
  path: ^1.9.0
  # 路由导航
  go_router: ^17.0.0
  # 音频库
  just_audio: ^0.10.5
  # 文本组件
  ruby_text: ^3.0.3
  # 动画
  flutter_animate: ^4.5.0
  # 手势操作
  gesture_x_detector: ^1.1.1
  # JSON
  json_annotation: ^4.9.0
  # 英文转罗马音
  kana_kit: ^2.1.1
  # 沙盒路径获取
  path_provider: ^2.1.3
  # 网络请求
  dio: ^5.7.0
  # 日志
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/database/breeze_jp.sqlite
    - assets/audio/words/
    - assets/audio/examples/
    